databases:
  - name: solar
    user: solar
    plan: free
    region: ohio

services:
  - type: web
    name: Solar Powered
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: solar
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false